a=input("Enter your string")
k=a.count("a")
k=k+a.count("A")
k=k+a.count("e")
k=k+a.count("E")
k=k+a.count("i")
k=k+a.count("I")
k=k+a.count("o")
k=k+a.count("O")
k=k+a.count("u")
k=k+a.count("U")
print("Number of vowels in the string is:",k)